---
# tasks file for CiscoUse.ucs/lan/inband_profiles
- name: UCS Inband Profiles Configuration

  vars:
    login_info: &login_info
      hostname: "{{ ucs_hostname }}"
      username: "{{ ucs_username }}"
      password: "{{ ucs_password }}"
      state: "{{ ucs_state }}"

  block:
  - name: Configure Inband Profiles
    ucs_managed_objects:
      <<: *login_info
      objects: "{{ item.objects }}" 
    when: item.objects is defined
    with_items: "{{ ucs_inband_profiles }}"
