---
# tasks file for CiscoUcs.ucs/chassis/chassis_maintenance_policies
- name: UCS Chassis Maintenance Policy Configuration

  vars:
    login_info: &login_info
      hostname: "{{ ucs_hostname }}"
      username: "{{ ucs_username }}"
      password: "{{ ucs_password }}"
      state: "{{ ucs_state }}"

  block:
  - name: Configure Chassis Maintenance Policy
    ucs_chassis_maintenance:
      <<: *login_info
      name: "{{ item.name }}"
      description: "{{ item.description | default(omit) }}"
    when: item.name is defined
    with_items: "{{ ucs_chassis_maintenance_policies }}"
