---
# tasks file for CiscoUcs.ucs/chassis/chassis_profiles_from_template
- name: UCS Chassis Profile from Template Configuration

  vars:
    login_info: &login_info
      hostname: "{{ ucs_hostname }}"
      username: "{{ ucs_username }}"
      password: "{{ ucs_password }}"
      state: "{{ ucs_state }}"

  block:
  - name: Configure Chassis Profiles from Templates
    ucs_chassis_profile_from_template:
      <<: *login_info
      name: "{{ item.name }}"
      description: "{{ item.description | default(omit) }}"
      source_template: "{{ item.source_template }}"
    when: item.name is defined
    with_items: "{{ ucs_chassis_profiles_from_templates }}"
