---
# tasks file for CiscoUcs.ucs/servers/boot_policies
- name: UCS Boot Policy Configuration

  vars:
    login_info: &login_info
      hostname: "{{ ucs_hostname }}"
      username: "{{ ucs_username }}"
      password: "{{ ucs_password }}"
      state: "{{ ucs_state }}"

  block:
  - name: Configure Boot Policies
    ucs_managed_objects:
      <<: *login_info
      objects: "{{ item.objects }}" 
    when: item.objects is defined
    with_items: "{{ ucs_boot_policies }}"
